### ISSUE TITLE
Adding the CoLA classifier to Huggingface

### ISSUE THREAD

**Issue by avidale** [martiansideofthemoon/style-transfer-paraphrase#36]
Hello everyone (especially @martiansideofthemoon, I believe) and thank you for the brilliant paper!

Our team have used your CoLA classifier to evaluate fluency in our project on text detoxification (https://github.com/skoltech-nlp/detox), and it showed better correlation with human judgements of fluency than alternative models trained on CoLA. Therefore, we suggest to use this classifier in other projects on text style transfer. 

Could you please upload the classifier to the Huggingface model repository (or give us permission to do so), to make this classifier more conveniently accessible in other projects?

**Comment by martiansideofthemoon** [comment]
Hi @avidale,
Thanks for your interest & your report of successfully using the CoLA classifier. Yes please feel free to upload it if you have the bandwidth to do so, would be great if you could point me to the HuggingFace link so that I can add it to this repository. I will probably be able to get to this only after a few weeks.

**Comment by avidale** [comment]
Here it is: https://huggingface.co/cointegrated/roberta-large-cola-krishna2020

**Comment by martiansideofthemoon** [comment]
Thank you @avidale! I've added a note in the README - https://github.com/martiansideofthemoon/style-transfer-paraphrase#updates-2021
